package com.springdatajpa.MongoDBExample;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import com.springdatajpa.MongoDBExample.dto.CustomerDTO;
import com.springdatajpa.MongoDBExample.service.CustomerService;

/*
 * 
 * 	Customer Info stored with ID: 1
	Customer Info stored with ID: 2
	Customer Info stored with ID: 3
	
	Document with id: 3445 not found
	
	Customer [id=672c8db5390117b7f00d8190, custNo=null, name=Name1, city=Corpus_Christi]
	Customer [id=1, custNo=3234, name=Name1, city=Corpus_Christi]
	Customer [id=2, custNo=3224, name=Name2, city=Spokane]
	Customer [id=3, custNo=4224, name=Name3, city=Boise]
 */

/*
 * second output ID without custom input: id generated by MongoDB
 * 
 * 	Customer Info stored with ID: 672d190e7f2e822d9b0b1dd9
	Customer Info stored with ID: 672d190e7f2e822d9b0b1dda
	Customer Info stored with ID: 672d190e7f2e822d9b0b1ddb

	Document with id: 3445 not found
	
	Customer [id=672c8db5390117b7f00d8190, custNo=null, name=Name1, city=Corpus_Christi]
	Customer [id=1, custNo=3234, name=Name1, city=Corpus_Christi]
	Customer [id=2, custNo=3224, name=Name2, city=Spokane]
	Customer [id=3, custNo=4224, name=Name3, city=Boise]
	Customer [id=672d190e7f2e822d9b0b1dd9, custNo=3234, name=Name1, city=Corpus_Christi]
	Customer [id=672d190e7f2e822d9b0b1dda, custNo=3224, name=Name2, city=Spokane]
	Customer [id=672d190e7f2e822d9b0b1ddb, custNo=4224, name=Name3, city=Boise]
 */

@SpringBootApplication
public class MongoDbExampleApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext IOCcontainer = SpringApplication.run(MongoDbExampleApplication.class, args);
		CustomerService custBean = IOCcontainer.getBean(CustomerService.class);
		/* our id is given here
		CustomerDTO dto = new CustomerDTO("1", 3234, "Name1", "Corpus_Christi");
		String status = custBean.registerCustomer(dto);
		System.out.println(status);
		*/
		
		// i have removed id from constructors of classes so MongoDB is generating IDs
		CustomerDTO dto = new CustomerDTO(3234, "Name1", "Corpus_Christi");
		String status = custBean.registerCustomer(dto);
		System.out.println(status);
		
		CustomerDTO dto1 = new CustomerDTO(3224, "Name2", "Spokane");
		status = custBean.registerCustomer(dto1);
		System.out.println(status);
		
		CustomerDTO dto2 = new CustomerDTO(4224, "Name3", "Boise");
		status = custBean.registerCustomer(dto2);
		System.out.println(status);

		status=custBean.removeDocument("3445"); //random ID
		System.out.println(status);
		custBean.findAllCustomers().forEach(v->System.out.println(v));
	}

}
